# Test Gallery Generator
# This script creates a local preview of the plot gallery

from pathlib import Path

# Get test directory
test_dir = Path(__file__).parent / "tests"
plots = list(test_dir.glob("*.png"))

if not plots:
    print("No plots found! Run 'pytest tests/test_plotting.py' first.")
    exit(1)

html_content = """<!DOCTYPE html>
<html>
<head>
    <title>CRFlux Plot Gallery - Local Preview</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        h1 {
            color: #333;
            border-bottom: 3px solid #0366d6;
            padding-bottom: 10px;
        }
        .plot-container {
            background: white;
            border-radius: 8px;
            padding: 20px;
            margin: 20px 0;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .plot-container h2 {
            color: #0366d6;
            margin-top: 0;
        }
        .plot-container img {
            max-width: 100%;
            height: auto;
            border: 1px solid #ddd;
            border-radius: 4px;
        }
        .info {
            background-color: #e1f5fe;
            border-left: 4px solid #0366d6;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        .timestamp {
            color: #666;
            font-size: 0.9em;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h1>🌌 CRFlux Model Comparison Plots</h1>
    
    <div class="info">
        <strong>About:</strong> These plots compare various cosmic ray flux models implemented in the crflux package.
        The plots are automatically generated by the test suite.
    </div>
"""

plot_info = {
    "nucleon_flux.png": ("Nucleon Flux", "Cosmic ray nucleon flux (proton + neutron) for different models."),
    "neutron_fraction.png": ("Neutron Fraction", "Fraction of neutrons relative to protons across different energies."),
    "total_flux.png": ("Total Particle Flux", "Cosmic ray particle flux for all nuclei combined."),
    "mean_log_mass.png": ("Mean Log Mass", "Mean logarithmic mass &lt;ln A&gt; as a function of energy."),
    "nucleon_flux_ratio.png": ("Nucleon Flux Ratio", "Ratio of nucleon flux relative to GSF2025 model."),
    "total_flux_ratio.png": ("Total Flux Ratio", "Ratio of total particle flux relative to GSF2025 model."),
}

for plot_file in sorted(plots):
    filename = plot_file.name
    if filename in plot_info:
        title, description = plot_info[filename]
        html_content += f"""
    <div class="plot-container">
        <h2>{title}</h2>
        <p>{description}</p>
        <img src="tests/{filename}" alt="{title}">
    </div>
"""

html_content += """
    <div class="timestamp">
        This is a local preview. In CI, the gallery will be automatically generated and deployed.
    </div>
</body>
</html>
"""

# Write HTML file
output_file = Path(__file__).parent / "plot_gallery_preview.html"
with open(output_file, "w", encoding="utf-8") as f:
    f.write(html_content)

print(f"✅ Gallery preview created: {output_file}")
print(f"📊 Found {len(plots)} plots")
print(f"\nOpen in browser: file:///{output_file.absolute()}")
